const investigationCards = document.querySelectorAll(".investigation-card");
const inputLabel = document.getElementById("inputLabel");
const investigationInput = document.getElementById("investigationInput");
const analyzeButton = document.getElementById("analyzeButton");
const result = document.getElementById("result");

let currentType = "message";

const investigationTypes = {
    message: {
        label: "Paste the suspicious message",
        placeholder: "Paste a suspicious message here..."
    },
    email: {
        label: "Paste the suspicious email",
        placeholder: "Paste the email content here..."
    },
    url: {
        label: "Enter the suspicious website URL",
        placeholder: "Example: https://example.com"
    },
    phone: {
        label: "Enter the phone number",
        placeholder: "Example: +91 9876543210"
    },
    person: {
        label: "Enter the person's public identity information",
        placeholder: "Enter their claimed name, organization, website, or public profile..."
    },
    company: {
        label: "Enter the company information",
        placeholder: "Enter the company name, website, or email domain..."
    }
};

investigationCards.forEach(function(card) {

    card.addEventListener("click", function() {

        investigationCards.forEach(function(item) {
            item.classList.remove("active");
        });

        card.classList.add("active");

        currentType = card.dataset.type;

        inputLabel.textContent = investigationTypes[currentType].label;
        investigationInput.placeholder =
            investigationTypes[currentType].placeholder;

        investigationInput.value = "";

        resetResult();
    });

});


analyzeButton.addEventListener("click", function() {

    const input = investigationInput.value.trim();

    if (input === "") {

        result.innerHTML =
            '<div class="result-header">' +
            '<h2>Investigation Report</h2>' +
            '<span class="status-badge">INPUT REQUIRED</span>' +
            '</div>' +
            '<p class="result-placeholder">' +
            'Please enter something to investigate first.' +
            '</p>';

        return;
    }

    result.innerHTML =
        '<div class="result-header">' +
        '<h2>Investigation Report</h2>' +
        '<span class="status-badge">ANALYZING</span>' +
        '</div>' +
        '<p class="result-placeholder">' +
        'PhishLens is analyzing your input...' +
        '</p>';

    setTimeout(function() {
        showDemoResult(input);
    }, 800);

});


function showDemoResult(input) {

    const typeName =
        currentType.charAt(0).toUpperCase() +
        currentType.slice(1);

    result.innerHTML =
        '<div class="result-header">' +
        '<h2>Investigation Report</h2>' +
        '<span class="status-badge">DEMO</span>' +
        '</div>' +

        '<div class="analysis-content">' +

        '<p><strong>Investigation type:</strong> ' +
        typeName +
        '</p>' +

        '<p><strong>Input received:</strong> ' +
        escapeHTML(input) +
        '</p>' +

        '<h3>Evidence Summary</h3>' +

        '<ul>' +
        '<li>Input successfully received by PhishLens.</li>' +
        '<li>Investigation type identified as ' +
        typeName +
        '.</li>' +
        '<li>Backend analysis is not connected yet.</li>' +
        '</ul>' +

        '<h3>AI Assessment</h3>' +

        '<p>This is currently a frontend demonstration. ' +
        'The real risk assessment will be generated by the ' +
        'PhishLens backend and AI model.</p>' +

        '</div>';
}


function resetResult() {

    result.innerHTML =
        '<div class="result-header">' +
        '<h2>Investigation Report</h2>' +
        '<span class="status-badge">WAITING</span>' +
        '</div>' +

        '<p class="result-placeholder">' +
        'Your investigation results will appear here.' +
        '</p>';
}


function escapeHTML(text) {

    const div = document.createElement("div");

    div.textContent = text;

    return div.innerHTML;
}